#! /bin/bash
if [[ -f /etc/startup_was_launched ]]; then exit 0; fi
apt update
apt -y install apache2 php libapache2-mod-php

gsutil cp -r gs://barrychumtemp/html/* /var/www/html

touch /etc/startup_was_launched 
cat <<EOF > /var/www/html/phpinfo.php
<?php phpinfo(); ?>
